version: '2.1'

jobs:
  build:
    docker:
        - image: cimg/ruby:3.1.2
    working_directory: ~/her.sh
    environment:
      - JEKYLL_ENV: "production"
    steps:
      - checkout
      - run: rake setup
      - run: rake build
      - run: rake lint
      - persist_to_workspace:
          root: ~/her.sh
          paths: _site

  deploy:
    docker:
        - image: cimg/python:3.11.0
    working_directory: ~/her.sh
    steps:
      - checkout
      - run: |
          pip install s3cmd
          s3cmd --version
      - attach_workspace:
          at: ~/her.sh
      - run: .circleci/publish.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          context: Pushover
          requires:
            - build
          filters:
            branches:
              only: master
