// misc stuff

function greets() {
	var greets = new Array(
		"Yo.",
		"Sup.",
		"Hi.",
		"Hey."
	);
	
	var key = Math.round(Math.random()*(greets.length-1));
	
	$("h2#greetings").html( greets[key] );
}

function punctuate() {
	var punctuation = new Array(
		".",
		"?",
		"!",
		";"
	);
	
	var key = Math.round(Math.random()*(punctuation.length-1));
	
	$("a#punctuation").html( punctuation[key] );
}

function taglineTimer() {
	$("#tagline").fadeOut(250);
    setTimeout("setTagline();", 250 );
    setTimeout("$('#tagline').fadeIn(250);", 250);

	setTimeout("taglineTimer();", 7500 );
}

function getRandTagline() {
	var arr2 = new Array(
			"Internet citizen",
			"world-champion skydiver",
			"inventor of sliced bread",
			"competitive eater",
			"binary mixologist",
			"philosopher",
			"gentleman and scholar",
			"tacologist",
			"wiki-wikipedia!",
			"technologist",
			"west-coast transplant",
			"artiste nouveau",
			"rock band drummer",
			"philosopher",
			"a.k.a. @jhersh",
			"blue three",
			"superhero",
			"silicon artist",
			"destroyer of sushi",
			"computer whisperer",
			"cruciverbalist",
			"member of the Twitterati"
		);
			
	var size2 = arr2.length;

	var key2 = Math.round(Math.random()*(size2-1));
	
	return arr2[key2];
}

function setTagline() {
	var res = getRandTagline();

	//$("#tagline").fadeOut(250);
	document.getElementById( "tagline" ).innerHTML = res;
	//setTimeout("$('#tagline').fadeIn(250);", 250);
	
	mpmetrics.track('factoid');
}


function getRandSaying() {
	var arr = new Array(
			"It's impossible to sneeze with your eyes open. ",
			"The name Wendy was made up for the book \"Peter Pan.\"",
			"Sherlock Holmes never said \"Elementary, my dear Watson.\"",
			"A person swallows an average of 7-8 spiders in their lifetime.",
			"In 10 minutes, a hurricane releases more energy than all the world's nuclear weapons combined.",
			"The average person falls asleep in seven minutes.",
			"Every time you lick a stamp, you're consuming 1/10 of a calorie.",
			"The record number of people crammed into a 1998 Volkswagon Bug and still able to close all doors is 18.",
			"13 people are killed every year from falling vending machines.",
			"Captain Kirk never said \"Beam me up, Scotty\".",
			"\"Stewardesses\" is the longest word that is typed with only the left hand.",
			"\"Typewriter\" is the longest word that is typed only on one row of the keyboard.",
			"Facetious and abstemious contain all the vowels in the correct order, as does arsenious, meaning \"containing arsenic.\"",
			"The word \"Checkmate\" in chess comes from the Persian phrase \"Shah Mat,\" which means \"the king is dead\".",
			"The verb \"cleave\" is the only English word with two synonyms which are antonyms of each other: adhere and separate.",
			"Lollipop is the longest word you can type with only your right hand.",
			"The most common name in Italy is Mario Rossi.",
			"Paul Revere rode on a borrowed horse that belonged to Deacon Larkin.",
			"Roosters can't crow if they can't fully extend their necks.",
			"There are only three types of snakes on the island of Tasmania and all are deadly poisonous.",
			"Assuming Rudolph was in front, there are 40320 ways to arrange the other eight reindeer.",
			"The dial tone of a normal telephone is in the key of \"F\".",
			"Emus have double-plumed feathers, and they lay emerald/forest green eggs.",
			"\"Corduroy\" comes from the French \"cord du roi\" or \"cloth of the king.\"",
			"The permanent teeth that erupt to replace their primary predecessors (baby teeth) are called succedaneous teeth.",
			"\"Polish\" is the only word in the English language that when capitalized is changed from a noun or a verb to a nationality.",
			"Only five countries in Europe touch only one other: Portugal, Denmark, San Marino, Vatican City, and Monaco.",	
			"The original IBM punchcard is the same size as a Civil War era dollar bill.",
			"The concave dish shape that a liquid takes on inside a glass or tube is called a meniscus.",
			"Croatia was the first country to recognize the United States in 1776.",
			"The white part of your fingernail is called the lunula.",
			"Emus and kangaroos cannot walk backwards, and are on the Australian coat of arms for that reason.",
			"Cats have over one hundred vocal sounds, while dogs only have about ten.",
			"The ship \"Queen Elizabeth 2\" should always be written as QE2. QEII is the actual queen.",
			"\"Quisling\" is the only word in the English language to start with \"quis.\"",
			"When a coffee seed is planted, it takes five years to yield consumable fruit.",
			"The common goldfish is the only animal that can see both infra-red and ultra-violet light.",
			"The infinity sign is called a lemniscate.",
			"The westernmost point in the contiguous United States is Cape Alava, Washington.",
			"If you stretch a standard Slinky out flat it measures 87 feet long.",
			"There are six words in the English language with the letter combination \"uu.\" Muumuu, vacuum, continuum, duumvirate, duumvir and residuum.",
			"The pupil of an octopus' eye is rectangular.",
			"The shortest French word with all five vowels is \"oiseau\", meaning bird.",
			"The ball on top of a flagpole is called the truck.",
			"In the last 4000 years, no new animals have been domesticated.",
			"The first prime number after 1,000,000 is 1,000,003.",
			"The most popular sport as a topic for a film is boxing.",
			"Walt Disney's autograph bears no resemblance to the famous Disney logo.",
			"Other than humans, black lemurs are the only primates that may have blue eyes.",
			"Since 1896, the beginning of the modern Olympics, only Greece and Australia have participated in every Games.",
			"The only member of the band ZZ Top without a beard has the last name Beard.",
			"The letters H, I, O, and X in the Latin alphabet are the only ones that look the same if you turn them upside down or see them from behind.",
			"Vincent Van Gogh sold exactly one painting while he was alive, Red Vineyard at Arles.",
			"There is actually a word for a 64th note -- a hemidemisemiquaver.",
			"A peanut is not a nut; it is a legume.",
			"A baby eel is called an elver, a baby oyster is called a spat.",
			"There are only 12 letters in the Hawaiian alphabet.",
			"Armored knights raised their visors to identify themselves when they rode past their king. This custom has become the modern military salute.",
			"21978 x 4 = 87912.",
			"The hundred billionth crayon made by Crayola was Perriwinkle Blue.",
			"The legbones of a bat are so thin that no bat can walk.",
			"Charles Lindbergh took only four sandwiches with him on his famous transatlantic flight.",
			"A full moon always rises at sunset.",
			"If you are locked in a completely sealed room, you will die of carbon dioxide poisoning first before you will die of oxygen deprivation.",
			"Moon was Buzz Aldrin's mother's maiden name.",
			"A Macintosh LC575 has 182 speaker holes.",
			"M & M's were developed so that soldiers could eat candy without getting their fingers sticky.",
			"Carnivorous animals will not eat another animal that has been hit by a lightning strike.",
			"Reindeer milk has more fat than cow milk.",
			"Libya is the only country in the world with a solid, single-colored flag -- it's green.",
			"Seoul, the South Korean capital, just means \"the capital\" in Korean.",
			"The word \"freelance\" comes from a knight whose lance was free for hire, i.e. not pledged to one master.",
			"Crows have the largest cerebral hemispheres, relative to body size, of any avian family.",
			"The Old English word for \"sneeze\" is \"fneosan.\"",
			"Almost half the bones in your body are in your hands and feet.",
			"A flamingo can eat only when its head is upside down.",
			"The average garden variety caterpillar has 248 muscles in its head.",
			"An elephant can be pregnant for up to two years.",
			"Cranberry Jello is the only jello flavor that comes from real fruit, not artificial flavoring.",
			"The Soviet Sukhoi-34 is the first strike fighter with a toilet in it.",
			"\"Video Killed the Radio Star\" was the very first video ever played on MTV.",
			"An enneahedron is solid with nine faces.",
			"Cleopatra used pomegranate seeds for lipstick.",
			"The raised reflective dots in the middle of highways are called Botz dots.",
			"Starfish don't have brains.",
			"Mosquito repellents don't repel. They hide you. The spray blocks the mosquito's sensors so they don't know you're there.",
			"The liquid inside young coconuts can be used as substitute for blood plasma.",
			"No piece of paper can be folded in half more than 7 times. Try it.",
			"Donkeys kill more people annually than plane crashes.",
			"You burn more calories sleeping than you do watching television.",
			"Oak trees do not produce acorns until they are fifty years of age or older.",
			"The first product to have a bar code was chewing gum.",
			"The king of hearts is the only king without a moustache.",
			"A Boeing 747's wingspan is longer than the Wright brothers' first flight.",
			"American Airlines saved $40,000 in 1987 by eliminating 1 olive from each salad served in first-class.",
			"The first CD pressed in the US was Bruce Springsteen's 'Born in the USA.'",
			"Apples, not caffeine, are more efficient at waking you up in the morning.",
			"The plastic things on the end of shoelaces are called aglets.",
			"Most dust particles in your house are made from dead skin.",
			"Barbie's full name is Barbara Millicent Roberts.",
			"Michael Jordan makes more money from Nike annually than all of the Nike factory workers in Malaysia combined.",
			"The word 'samba' means 'to rub navels together.'",
			"Grabatology is the collecting of ties.",
			"Money isn't made out of paper, it's made out of cotton.",
			"There is no single word given to describe the back of the knee.",
			"The average American has two credit cards.",
			"The international telephone area code for Antarctica is 672.",
			"The cigarette lighter was invented before the match.",
			"There are coffee flavored PEZ.",
			"'Go hang a salami - I'm a lasagna hog' is a palindrome.",
			"In medieval England beer was often served with breakfast.",
			"The Atlantic Ocean is saltier then the Pacific Ocean.",
			"Only female mosquitoes bite.",
			"There are more stars in the universe than grains of sand on all the beaches in the world.",
			"Every day more money is printed for monopoly than for the US Treasury.",
			"Men get hiccups more often than women.",
			"The average life span of a major league baseball is 7 pitches.",
			"7% of Americans will eat McDonalds today.",
			"The only bird that can fly backwards is the Hummingbird.",
			"The youngest Pope was 11 years old.",
			"There are 240 white dots on a Pac-man video game.",
			"Pearls melt in vinegar.",
			"The 3 most valuable brand names on earth: Marlboro, Coca-Cola and Budweiser (in that order).",
			"Humans are the only primates that don't have pigment in the palms of their hands.",
			"The sentence 'The quick brown fox jumps over the lazy dog.' uses every letter in the alphabet.",
			"10% of the Russian government's income comes from the sale of vodka.",
			"The only 15 letter word that can be spelled without repeating a letter is 'uncopyrightable.'",
			"Each king in a deck of playing cards represents a great king from history. Spades - King David; Clubs - Alexander the Great; Hearts - Charlemagne; Diamonds - Julius Caesar.",
			"111,111,111 x 111,111,111 = 12,345,678,987,654,321.",
			"An ostrich's eye is bigger than its brain.",
			"The longest recorded flight of a chicken is thirteen seconds.",
			"Only one person in two billion will live to be 116 or older.",
			"Nine pennies weigh exactly one ounce.",
			"Rubber bands last longer when refrigerated.",
			"Peanuts are one of the ingredients of dynamite.",
			"There are 293 ways to make change for a dollar.",
			"The average person's left hand does 56% of the typing.",
			"There are more chickens than people in the world.",
			"The longest one-syllable words in the English language are Screeched, Scratched, Scrounged, Scrunched, Splotched, Squished and Squelched.",
			"Most of the clocks in the movie 'Pulp Fiction' are stuck on 4:20.",
			"No word in the English language rhymes with: month, orange, silver or purple.",
			"'Dreamt' is the only English word that ends in the letters 'mt.'",
			"Almonds are a member of the peach family.",
			"Maine is the only US state whose name is just one syllable.",
			"There are only four words in the English language which end in '-dous': tremendous, horrendous, stupendous and hazardous.",
			"A cat has 32 muscles in each ear.",
			"Tigers have striped skin as well as striped fur.",
			"In most advertisements (including newspapers) the time displayed on a watch is 10:10.",
			"A dime has 118 ridges around the edge.",
			"There are 336 dimples on a regulation golf ball.",
			"If you were to spell out numbers you would have to go up to one thousand before you would find the letter 'A'.",
			"Mel Blanc (the voice of Bugs Bunny) was allergic to carrots.",
			"An animal epidemic is called an epizootic.",
			"Reindeer like to eat bananas.",
			"The United States has never lost a war in which mules were used.",
			"More people are killed each year by bee stings than shark attacks.",
			"The only nation whose name begins with an 'A' but doesn't end in an 'A' is Afghanistan.",
			"It's impossible to sneeze with your eyes open.",
			"Your stomach has to produce a new layer of mucus every two weeks otherwise it will digest itself.",
			"The world's only B.A. Program in bagpiping is taught at Carnegie Mellon University by James McIntosh.",
			"There are four cars and eleven light posts on the back of a ten-dollar bill.",
			"Pinocchio is Italian for \"pine head.\"",
			"Sarsaparilla is the root that flavors root beer.",
			"American car horns beep in the tone of F.",
			"Donkeys kill more people annually than plane crashes.",
			"1 in every 4 Americans has appeared on television.",
			"You burn more calories sleeping than you do watching television.",
			"Oak trees do not produce acorns until they are fifty years of age or older.",
			"The first product to have a bar code was chewing gum.",
			"The king of hearts is the only king without a moustache.",
			"A type of jellyfish found off the coast of England is the longest animal in the world.", 
			"Crows have the largest cerebral hemispheres, relative to body size, of any avian family.", 
			"The Old English word for \"sneeze\" is \"fneosan.\"",
			"Elizabeth I suffered from anthophobia, a fear of roses.", 
			"Almost half the bones in your body are in your hands and feet.",
			"A flamingo can eat only when its head is upside down.", 
			"The average garden variety caterpillar has 248 muscles in its head.",
			"An elephant can be pregnant for up to two years. ",
			"Dartboards are made out of horsehairs. ",
			"Heroin is the brand name of morphine once marketed by Bayer. ",
			"One of the many Tarzans, Karmuela Searlel, was mauled to death on the set by a raging elephant.", 
			"The youngest letters in the English language are \"j,\" \"v\" and \"w.\" ",
			"The Australian $5, $10, $20, $50 and $100 notes are made out of plastic.", 
			"Cranberry Jello is the only jello flavor that comes from real fruit, not artificial flavoring.", 
			"The Soviet Sukhoi-34 is the first strike fighter with a toilet in it. ",
			"The tango originated as a dance between two men (for partnering practice.) ",
			"\"Video Killed the Radio Star\" was the very first video ever played on MTV.", 
			"During WWII, Americans tried to train bats to drop bombs. ",
			"An enneahedron is solid with nine faces. ",
			"Jet lag was once called boat lag, back before jets existed. ",
			"There are more beetles than any other kind of creature in the world. ",
			"Velcro was invented by a Swiss guy who was inspired by the way burrs attached to clothing. ",
			"The Egyptian hieroglyph for 100,000 is a tadpole.",
			
			
			"The liquid inside young coconuts can be used as substitute for blood plasma.",
"American car horns beep in the tone of F.",
"No piece of paper can be folded in half more than 7 times.",
"Donkeys kill more people annually than plane crashes.",
"1 in every 4 Americans has appeared on television.",
"You burn more calories sleeping than you do watching television.",
"Oak trees do not produce acorns until they are fifty years of age or older.",
"The first product to have a bar code was chewing gum.",
"The king of hearts is the only king without a moustache.",
"A Boeing 747's wingspan is longer than the Wright brother's first flight.",
"Venus is the only planet that rotates clockwise.",
"The first CD pressed in the US was Bruce Springsteen's 'Born in the USA.'",
"Apples, not caffeine, are more efficient at waking you up in the morning.",
"The plastic things on the end of shoelaces are called aglets.",
"Most dust particles in your house are made from dead skin.",
"The first owner of the Marlboro company died of lung cancer.",
"Barbie's full name is Barbara Millicent Roberts.",
"The shortest poem in the world is 'Fleas'.",
"The most common name in the world is Mohammed.",
"The word 'samba' means 'to rub navels together.'",
"Conception occurs more often in December than any other month.",
"Half of all Americans live within 50 miles of their birthplace. This is an effect known as propinquity.",
"Grabatology is the collecting of ties.",
"Human hair and fingernails continue to grow after death.",
"There is no single word given to describe the back of the knee.",
"Money isn't made out of paper, it's made out of cotton.",
"The average American has two credits cards.",
"The international telephone area code for Antarctica is 672.",
"The glue on postage stamps in Israel is certified kosher.",
"A 'Jiffy' is actually a unit of time for 1/100th of a second.",
"On average 100 people choke to death on ballpoint pens every year.",
"In 10 minutes a hurricane releases more energy than all the world's nuclear weapons combined.",
"The average age of the Rolling Stones is 50.6.",
"Elephants can't jump. Every other mammal can.",
"The cigarette lighter was invented before the match.",
"Five Jell-O flavors that flopped are celery, coffee, cola, apple and chocolate.",
"There are coffee flavored PEZ.",
"'Go hang a salami - I'm a lasagna hog' is a palindrome.",
"The Atlantic Ocean is saltier then the Pacific Ocean.",
"In medieval England beer was often served with breakfast.",
"The right lung takes in more air then the left. ",
"At 90 degrees (F) below zero, your breath will freeze in midair and fall to the ground.",
"There are more stars in the universe than grains of sand on all the beaches in the world.",
"Every day more money is printed for monopoly than for the US Treasury.",
"Men get hiccups more often than women.",
"Men can read smaller print than women.",
"Women can hear better than men.",
"The average life span of a major league baseball is 7 pitches.",
"7% of Americans will eat McDonalds today.",
"The chances that a burglary in the US will be solved is 1 in 7.",
"The only bird that can fly backwards is the Hummingbird.",
"Polar bears are left handed.",
"The world's youngest parents were 8 and 9 and lived in China.",
"The youngest Pope was 11 years old.",
"Your nose and ears never stop growing.",
"If an insect flies in your ear, shine a light in and it will probably crawl or fly back out.",
"There are 240 white dots on a Pac-man video game.",
"According to Genesis 1:20-22, the chicken came before the egg.",
"'Race car' is a palindrome.",
"Debra Winger was the voice of E.T.",
"Pearls melt in vinegar.",
"While performing her duties as queen Cleopatra sometimes wore a fake beard.",
"It takes 3 000 cows to supply the NFL with enough leather for a year's supply of footballs.",
"Thirty-five percent of the people who use personal ads for dating are already married.",
"The 3 most valuable brand names on earth: Marlboro, Coca-Cola and Budweiser (in that order).",
"It's possible to lead a cow upstairs, but not downstairs.",
"Humans are the only primates that don't have pigment in the palms of their hands.",
"10% of the Russian government's income comes from the sale of vodka.",
"The sentence 'The quick brown fox jumps over the lazy dog.' uses every letter in the alphabet.",
"The only 15 letter word that can be spelled without repeating a letter is 'uncopyrightable.'",
"'Go!' is the shortest complete sentence in the English language.",
"111 111 111 x 111 111 111 = 12 345 678 987 654 321.",
"An ostrich's eye is bigger that it's brain.",
"The longest recorded flight of a chicken is thirteen seconds.",
"The name Jeep came from the abbreviation used in the army for the 'General Purpose' vehicle (GP).",
"The highest point in Pennsylvania is lower than the lowest point in Colorado.",
"Nutmeg is extremely poisonous if injected intravenously.",
"Only one person in two billion will live to be 116 or older.",
"In Cleveland Ohio it's illegal to catch mice without a hunting license.",
"Spain literally means 'the land of rabbits'.",
"Every Swiss citizen is required by law to have a bomb shelter or access to a bomb shelter.",
"Nine pennies weigh exactly one ounce.",
"Snails can sleep for 3 years without eating.",
"Tommy Lee Jones and Al Gore were roommates at Harvard.",
"By raising your legs slowly and laying on your back you can't sink in quicksand.",
"Months that begin on a Sunday will always have a Friday the 13th.",
"Rubber bands last longer when refrigerated.",
"Peanuts are one of the ingredients of dynamite.",
"The national anthem of Greece has 158 verses.",
"There are 293 ways to make change for a dollar.",
"The average person's left hand does 56% of the typing.",
"The shark is the only fish that can blink with both eyes.",
"There are more chickens than people in the world.",
"Two-thirds of the world's eggplant is grown in New Jersey.",
"Most of the clocks in the movie 'Pulp Fiction' are stuck on 4:20.",
"No word in the English language rhymes with: month, orange, silver or purple.",
"'Dreamt' is the only English word that ends in the letters 'mt.'",
"Almonds are a member of the peach family.",
"Winston Churchill was born in a ladies' toilet during a dance.",
"Maine is the only US state whose name is just one syllable.",
"Tigers have striped skin as well as striped fur.",
"In most advertisements (including newspapers) the time displayed on a watch is 10:10.",
"Al Capone's business card said he was a used furniture dealer.",
"A dragonfly has a lifespan of 24 hours.",
"A goldfish has a memory span of three seconds.",
"A dime has 118 ridges around the edge.",
"The giant squid has the largest eyes in the world.",
"The Speaker of the House is not allowed to speak.",
"There are 336 dimples on a regulation golf ball.",
"The most popular boat name requested is 'Obsession'.",
"All lottery winners put on weight after they win.",
"Bullet proof vests, fire escapes, windshield wipers and laser printers were all invented by women.",
"Married men change their underwear twice as often as single men.",
"Honey is the only food that doesn't spoil.",
"There are more reverse charged calls on Father's Day than any other day of the year.",
"Mel Blanc (the voice of Bugs Bunny) was allergic to carrots.",
"3.9% of all women surveyed say they never wear underwear.",
"Camel's milk does not curdle. ",
"A cat has 32 muscles in each ear. ",
"Cats urine glows under a black light. ",
"Murphy's Oil Soap is the chemical most commonly used to clean elephants. ",
"A pregnant goldfish is called a twit.",
"All porcupines float in water. ",
"An animal epidemic is called an epizootic. ",
"The United States has never lost a war in which mules were used. ",
"Reindeer like to eat bananas. ",
"A pig's orgasm lasts for 30 minutes. ",
"Dolphins are the only animals that have sex for pleasure besides humans. ",
"More people are killed each year by bee stings than shark attacks.",
"Many hamsters only blink one eye at a time. ",
"Hang On Snoopy is the official rock song of Ohio. ",
"The highest point in Pennsylvania is lower than the lowest point in Colorado. ",
"The only nation who's name begins with an \"A\", but doesn't end in an \"A\" is Afghanistan. ",
"Montpelier, Vermont is the only U.S. state capital without a McDonald's. ",
"Non-dairy creamer is flammable. ",
"Tippex was invented by the mother of Mike Nesmith (Formerly of the Monkees). ",
"It's impossible to sneeze with your eyes open. ",
"The \"save\" icon on Microsoft Word shows a floppy disk with the shutter on backwards. ",
"Your stomach has to produce a new layer of mucus every two weeks otherwise it will digest itself. ",
"There are four cars and eleven light posts on the back of a ten-dollar bill. ",
"97% of all paper money in the US contains traces of cocaine. ",
"Pinocchio is Italian for \"pine head.\" ",
"The name Wendy was made up for the book \"Peter Pan.\" ",
"In Casablanca, Humphrey Bogart never said \"Play it again, Sam.\" ",
"Sherlock Holmes never said \"Elementary, my dear Watson.\" ",
"A person swallows an average of 7-8 spiders in their lifetime. ",
"In 10 minutes, a hurricane releases more energy than all the world's nuclear weapons combined. ",
"The average person falls asleep in seven minutes. ",
"Every time you lick a stamp, you're consuming 1/10 of a calorie. ",
"The sport that sends the most people to the ER is ping pong. ",
"13 people are killed every year from falling vending machines.",
"Captain Kirk never said \"Beam me up, Scotty\" ",
"\"Stewardesses\" is the longest word that is typed with only the left hand. ",
"Avocado is the Aztec word for testicle. ",
"Lollipop is the longest word you can type with only your right hand. ",
"Typewriter is the longest word that can be made using the letters on only one row of the keyboard.",
"The most common name in Italy is Mario Rossi. ",
"Paul Revere rode on a borrowed horse that belonged to Deacon Larkin. ",
"Roosters can't crow if they can't fully extend their necks. ",
"There are only three types of snakes on the island of Tasmania and all are deadly poisonous. ",
"Assuming Rudolph was in front, there are 40320 ways to arrange the other eight reindeer. ",
"Shirley Temple always had 56 curls in her hair. ",
"Hulk Hogan's real name is Terry Bollea. ",
"The dial tone of a normal telephone is in the key of \"F\". ",
"Emus have double-plumed feathers, and they lay emerald/forest green eggs. ",
"\"Corduroy\" comes from the French, \"cord du roi\" or \"cloth of the king.\" ",
"Tongeren is the oldest town in Belgium. ",
"The original IBM punchcard is the same size as a Civil War era dollar bill. ",
"The concave dish shape that a liquid takes on inside a glass or tube is called a meniscus. ",
"Croatia was the first country to recognize the United States in 1776. ",
"The white part of your fingernail is called the lunula. ",
"Emus and kangaroos cannot walk backwards, and are on the Australian coat of arms for that reason. ",
"Cats have over one hundred vocal sounds, while dogs only have about ten. ",
"The ship, the Queen Elizabeth 2, should always be written as QE2. QEII is the actual queen. ",
"\"Quisling\" is the only word in the English language to start with \"quis.\" ",
"When a coffee seed is planted, it takes five years to yield consumable fruit. ",
"The common goldfish is the only animal that can see both infra-red and ultra-violet light. ",
"The westernmost point in the contiguous United States is Cape Alava, Washington. ",
"The infinity sign is called a lemniscate. ",
"If you stretch a standard Slinky out flat it measures 87 feet long. ",
"Dirty Harry's badge number is 2211. ",
"The pupil of an octopus' eye is rectangular. ",
"The shortest French word with all five vowels is \"oiseau\" meaning bird. ",
"The ball on top of a flagpole is called the truck. ",
"Oliver Cromwell was hanged and decapitated two years after he had died. ",
"In the last 4000 years, no new animals have been domesticated. ",
"The first prime number after 1,000,000 is 1,000,003. ",
"Hamsters love to eat crickets. ",
"The Greek version of the Old Testament is called the Septuagent. ",
"The most popular sport as a topic for a film is boxing. ",
"Goat's eyes have rectangular pupils. ",
"Walt Disney's autograph bears no resemblance to the famous Disney logo. ",
"Other than humans, black lemurs are the only primates that may have blue eyes. ",
"The Ramses brand condom is named after the great phaoroh Ramses II who fathered over 160 children. ",
"The only member of the band ZZ Top without a beard has the last name Beard. ",
"Duelling is legal in Paraguay as long as both parties are registered blood donors. ",
"The metal part of a lamp that surrounds the bulb and supports the shade is called a harp. ",
"The metal part at the end of a pencil is twenty percent sulfur. ",
"Vincent Van Gogh sold exactly one painting while he was alive, Red Vineyard at Arles. ",
"Mr. Spock's blood type was T-Negative. ",
"There is actually a word for a 64th note -- a hemidemisemiquaver. ",
"A peanut is not a nut; it is a legume. ",
"\"Evian\" spelled backvards is naive. ",
"A baby eel is called an elver, a baby oyster is called a spat. ",
"Welsh mercenary bowmen in the medieval period only wore one shoe at a time. ",
"There are only 12 letters in the Hawaiian alphabet. ",
"Charles de Gaulle's final words were, \"It hurts.\" ",
"21978 x 4 = 87912. ",
"A robin's egg is blue, but if you put it in vinegar for thirty days it turns yellow. ",
"The hundred billionth crayon made by Crayola was Perriwinkle Blue. ",
"Montana mountain goats will butt heads so hard their hooves fall off. ",
"Spider Monkeys like banana daquiries. ",
"The legbones of a bat are so thin that no bat can walk. ",
"Fossilized dinosaur droppings are called coprolites, and are actually fairly common. ",
"Soldiers from every country salute with their right hand. ",
"Moisture, not air, causes superglue to dry. ",
"Charles Lindbergh took only four sandwiches with him on his famous transatlantic flight. ",
"Sarsaparilla is the root that flavors root beer. ",
"A full moon always rises at sunset. ",
"Moon was Buzz Aldrin's mother's maiden name. ",
"Rabbits love liquorice. ",
"A Macintosh LC575 has 182 speaker holes. ",
"Panama hats come from Ecuador not Panama. ",
"Human birth control pills work on gorillas. ",
"M & M's were developed so that soldiers could eat candy without getting their fingers sticky. ",
"The Grateful Dead were once called The Warlocks. ",
"Jersey was the only place that the Nazis occupied in Great Britain during World War II. ",
"The male gypsy moth can \"smell\" the virgin female gypsy moth from 1.8 miles away. ",
"Carnivorous animals will not eat another animal that has been hit by a lightning strike. ",
"Reindeer milk has more fat than cow milk. ",
"Libya is the only country in the world with a solid, single-colored flag -- it's green. ",
"Seoul, the South Korean capital, just means \"the capital\" in the Korean language. ",
"The female ferret is referred to as a jill. ",
"Alexander the Great was an epileptic. ",
"The only bone not broken so far during any ski accident is the one located in the inner ear. ",
"The word \"boondocks\" comes from the Tagalog (Filipino) word \"Bundok,\" which means mountain. ",
"The original plan for Disneyland included a Lilliputland. ",
"The word \"moose\" was originally Algonquin. ",
"The Sanskrit word for \"war\" means \"desire for more cows.\" ",
"A type of jellyfish found off the coast of England is the longest animal in the world. ",
"Crows have the largest cerebral hemispheres, relative to body size, of any avian family. ",
"The Old English word for \"sneeze\" is \"fneosan.\" ",
"Elizabeth I suffered from anthophobia, a fear of roses. ",
"Almost half the bones in your body are in your hands and feet. ",
"A flamingo can eat only when its head is upside down. ",
"The average garden variety caterpillar has 248 muscles in its head. ",
"An elephant can be pregnant for up to two years. ",
"Dartboards are made out of horsehairs. ",
"Heroin is the brand name of morphine once marketed by Bayer. ",
"One of the many Tarzans, Karmuela Searlel, was mauled to death on the set by a raging elephant. ",
"The youngest letters in the English language are \"j,\" \"v\" and \"w.\" ",
"The Australian $5, $10, $20, $50 and $100 notes are made out of plastic. ",
"Cranberry Jello is the only jello flavor that comes from real fruit, not artificial flavoring. ",
"The Soviet Sukhoi-34 is the first strike fighter with a toilet in it. ",
"The tango originated as a dance between two men (for partnering practice.) ",
"\"Video Killed the Radio Star\" was the very first video ever played on MTV. ",
"An enneahedron is solid with nine faces. ",
"Jet lag was once called boat lag, back before jets existed. ",
"There are more beetles than any other kind of creature in the world. ",
"Velcro was invented by a Swiss guy who was inspired by the way burrs attached to clothing. ",
"The Egyptian hieroglyph for 100,000 is a tadpole. ",
"Cleopatra used pomegranate seeds for lipstick. ",
"If you feed a seagull Alka-Seltzer, its stomach will explode. ",
"The raised reflective dots in the middle of highways are called Botz dots. ",
			
			
			
			
			"Her.sh is awesome."
		);
	

	
	var size = arr.length;

	var key = Math.round(Math.random()*(size-1));

	return new Array( key, size, arr[key] );	
}

function setFactoid() {
	var res = getRandSaying();
	//var tmp = "&nbsp;&nbsp;<a name=\"facts\" href=\"#facts\" onclick = \"setFactoid();\">Fact "+ 
		//(res[0]+1) +" of "+ (res[1]) +":</a> " + res[2];
	//var tmp = "&nbsp;&nbsp;<a name=\"facts\" href=\"#facts\" onclick = \"setFactoid();\">Fact #"+ 
	 var tmp ="<a href=\"#fa\" id=\"fa\" onclick=\"setFactoid();\">Factoid #"+
		(res[0]+1) +"</a>: " + res[2];

	document.getElementById( "factoid" ).innerHTML = tmp;
	//document.write(tmp);
}